### ISSUE TITLE
Use normalised counts as input

### ISSUE THREAD

**Issue by dominikburri** [pgrobecker/cellstates#10]
Hi Pascal,
The readme mentions that the input requires a table of "integer UMI counts". 
I'm wondering whether normalised UMI counts, e.g. from Sanity, could be used as well. Is this supported? Or can I transform normalised values back to integers for your method to work?

Best,
Dominik

**Comment by pgrobecker** [comment]
Hi Dominik,
The statistical model behind cellstates is based on the expected noise in UMI counts. If you use a non-integer input, it will simply round the values to the nearest integer. But since the statistics of the normalised data is different, it will not give the right results. 

If you want to use cellstates together with sanity, I would suggest to run cellstates first on the unnormalised data, sum up the UMI counts for each cluster and then run sanity on this. I think Jérémie has done this before, so maybe check with him.

Cheers,
Pascal

**Comment by dominikburri** [comment]
Hm okay, thank you! I will ask him.
